---
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port
    environment:
      - TZ=${TZ}
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      - DISABLE_IPV6=true
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
        # - JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - ./jellyfin/library:/config
      - ${TV_DIR}:/data/tvshows
      - ${MOVIES_DIR}:/data/movies
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096
        # - 8920:8920 #https webUI
      - 7359:7359/udp #local network discovery
        #- 1900:1900/udp #service discovery for DLNA and clients
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent/appdata:/config
      - ${DOWNLOADS_DIR}:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  # radarr:
  #   image: lscr.io/linuxserver/radarr:latest
  #   container_name: radarr
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   volumes:
  #     - ./radarr/data:/config
  #     - ${MOVIES_DIR}:/movies
  #     - ${DOWNLOADS_DIR}:/downloads
  #   ports:
  #     - 7878:7878
  #   restart: unless-stopped

  # sonarr:
  #   image: lscr.io/linuxserver/sonarr:latest
  #   container_name: sonarr
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   volumes:
  #     - ./sonarr/data:/config
  #     - ${TV_DIR}:/tv
  #     - ${DOWNLOADS_DIR}:/downloads
  #   ports:
  #     - 8989:8989
  #   restart: unless-stopped

  # prowlarr:
  #   image: lscr.io/linuxserver/prowlarr:latest
  #   container_name: prowlarr
  #   environment:
  #     - PUID={PUID}
  #     - PGID={PGID}
  #     - TZ={TZ}
  #   volumes:
  #     - ./prowlarr/data:/config
  #   ports:
  #     - 9696:9696
  #   restart: unless-stopped
